services:

  dnsmasq:
    container_name: dnsmasq
    image: labqs/dnsmasq:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dnsmasqbase
    restart: unless-stopped
    healthcheck:
      test: 'if [ -z "$(netstat -nltu |grep \:53)" ]; then exit 1;else exit 0;fi'
      interval: 2s
      timeout: 2s
      retries: 20
    cap_add:
      - 'NET_ADMIN'
    ports:
      - '53:53/udp'
    networks:
      - netlab01
    volumes:
      - $PWD./config:/etc/dnsmasq.d
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
