services:

  registry:
    container_name: registry
    image: docker.io/registry:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    networks:
      netlab01:
        ipv4_address: ${REGISTRY_HOST}
    volumes:
      - $PWD/config:/auth
      - registrydata:/var/lib/registry
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

volumes:
  registrydata:
    name: registrydata
    external: true

networks:
  netlab01:
    external: true
