services:

  registrydb:
    container_name: registrydb
    image: docker.io/registry:latest
    restart: unless-stopped
    ports:
      - ':5000'
    networks:
      - netlab01
    volumes:
      - registrydata:/var/lib/registry
      - $PWD/config/config.yml:/etc/docker/registry/config.yml
      - $PWD/auth:/auth
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

  registry:
    container_name: registry
    image: joxit/docker-registry-ui:latest
    restart: unless-stopped
    ports:
      - ':80'
    networks:
      - netlab01
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_SCAN_SUGGEST: false
      REGISTRY_TITLE: LabQS Docker Registry
      NGINX_PROXY_PASS_URL: http://registrydb:5000
      SINGLE_REGISTRY: true
      DELETE_IMAGES: false
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/registry`)
      - traefik.http.services.registry.loadbalancer.server.port=80
      - traefik.http.routers.registry.tls=true
      - traefik.http.middlewares.registry-stripprefix.stripprefix.prefixes=/registry
      - traefik.http.middlewares.registry-stripprefix.stripprefix.forceSlash=true
      - traefik.http.routers.registry.middlewares=registry-stripprefix@docker
      - SERVICE_NAME=registry

volumes:
  registrydata:
    name: registrydata
    external: true

networks:
  netlab01:
    external: true
