services:

  registrydb:
    container_name: registrydb
    image: docker.io/registry:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    networks:
      netlab01:
        ipv4_address: ${REGISTRYDB_HOST}
    volumes:
      - registrydata:/var/lib/registry
      - $PWD/config/config.yml:/etc/docker/registry/config.yml
      - $PWD/auth:/auth
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      # REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
      # REGISTRY_REDIS_ADDR: redis
      # REGISTRY_REDIS_PASSWORD: ${REDIS_PWD}

  registry:
    container_name: registry
    image: joxit/docker-registry-ui:latest
    restart: unless-stopped
    ports:
      - '8084:80'
    networks:
      netlab01:
        ipv4_address: ${REGISTRY_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_SCAN_SUGGEST: false
      REGISTRY_TITLE: LabQS Docker Registry
      NGINX_PROXY_PASS_URL: http://registrydb:5000
      SINGLE_REGISTRY: true
      DELETE_IMAGES: false

volumes:
  registrydata:
    name: registrydata
    external: true

networks:
  netlab01:
    external: true
