services:

  registry:
    container_name: registry
    image: registry:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    networks:
      netlab01:
        ipv4_address: ${REGISTRY_HOST}
    volumes:
      - registrydata:/var/lib/registry
      - /etc/zoneinfo:/etc/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - '8084:80'
    environment:
      - REGISTRY_TITLE=LabQS Docker Registry
      - REGISTRY_URL=http://${REGISTRY_HOST}:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry

volumes:
  registrydata:
    name: registrydata
    driver: local
