services:

  locust:
    container_name: locust
    image: locustio/locust:latest
    restart: unless-stopped
    ports:
      - '8089:8089'
      - '5557:5557'
    networks:
      netlab01:
        ipv4_address: ${LOCUST_HOST}
    volumes:
      - ${PWD}/config:/home/locust:rw
     environment:
      - HTTP_PROXY=http://locust:8089
      - HTTPS_PROXY=http://locust:8089
    command: 
      - '--config=master.conf'

  worker:
    container_name: locustworker
    image: locustio/locust
    volumes:
      - ${PWD}/config:/home/locust:rw
    command: 
      - '--worker'
      - '--master-host locust'