version: '3'

services:

  db:
    container_name: db
    hostname: db
    image: mysql:5.7
    ports:
      - "7364:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./shared_folder/mysql:/var/lib/mysql
      - ./docker_mysql:/docker-entrypoint-initdb.d

  teamtat:
    container_name: teamtat
    image: dongseop/teamtat:latest
    restart: unless-stopped
    ports:
      - '8090:3000'
    networks:
      netlab01:
        ipv4_address: ${TEAMTAT_HOST}
    volumes:
      - $PWD/mariadb/init:/docker-entrypoint-initdb.d:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: bash -c "wait-for-it db:3306 && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db

networks:
  netlab01:
    external: true
