services:

  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 90s
    ports:
      - '5400:5432'
    networks:
      netlab01:
        ipv4_address: ${POSTGRES_HOST}
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - $PWD/postgres/config:/etc/postgresql
      - $PWD/postgres/init:/docker-entrypoint-initdb.d
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: ${SVC_PWD}
      PGPASSFILE: /etc/postgresql/.pgpass

  postgres01:
    container_name: postgres01
    image: postgres:14
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 90s
    ports:
      - '5401:5432'
    networks:
      netlab01:
        ipv4_address: ${POSTGRES_HOST01}
    volumes:
      - postgresdata01:/var/lib/postgresql/data
      - $PWD/postgres01/config:/etc/postgresql
      - $PWD/postgres01/init:/docker-entrypoint-initdb.d
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: ${SVC_PWD_01}
      PGPASSFILE: /etc/postgresql/.pgpass

  postgres02:
    container_name: postgres02
    image: postgres:14
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 90s
    ports:
      - '5402:5432'
    networks:
      netlab01:
        ipv4_address: ${POSTGRES_HOST02}
    volumes:
      - postgresdata02:/var/lib/postgresql/data
      - $PWD/postgres02/config:/etc/postgresql
      - $PWD/postgres02/init:/docker-entrypoint-initdb.d
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: ${SVC_PWD_02}
      PGPASSFILE: /etc/postgresql/.pgpass

volumes:
  postgresdata:
    name: postgresdata
    external: true
  postgresdata01:
    name: postgresdata01
    external: true
  postgresdata02:
    name: postgresdata02
    external: true

networks:
  netlab01:
    external: true
