services:

  netbox:
    container_name: netbox
    image: lscr.io/linuxserver/netbox:latest
    restart: unless-stopped
    ports:
      - '8088:8080'
    networks:
      netlab01:
        ipv4_address: ${NETBOX_HOST}
    environment:
      TZ: America/Sao_Paulo
      SUPERUSER_EMAIL: maint@ita.br
      SUPERUSER_PASSWORD: ${SVC_PWD}
      ALLOWED_HOST: ${LAB_DOMAIN}
      BASE_PATH: /netbox
      DB_HOST: postgres
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: ${POSTGRES_PWD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PWD}
