services:

  certbot:
    container_name: certbot
    image: certbot/certbot
    ports:
      - '80:80'
      - '443:443'
    networks:
      netlab01:
        ipv4_address: ${CERTBOT_HOST}
    volumes:
      - $PWD/etc/letsencrypt:/etc/letsencrypt:rw
      - $PWD/var/lib/letsencrypt:/var/lib/letsencrypt:rw
      - $PWD/var/log:/var/log:rw
    command: 
      - 'certonly'
      - '--standalone'
      - '--agree-tos'
      - '-m gomesjm@ita.br'
      - '-n'
      - '-d ci.test.labqs.ita.br'
