services:

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    networks:
      netlab01:
        ipv4_address: ${CERTBOT_HOST}
    volumes:
      - $PWD/etc/letsencrypt:/etc/letsencrypt:rw
    command: [ "certbot", "certonly --standalone  --preferred-challenges http --agree-tos -n -d 'test.labqs.ita.br'"]