services:

  certbot:
    container_name: certbot
    image: certbot/certbot
    ports:
      - '80:80'
      - '443:443'
    networks:
      netlab01:
        ipv4_address: ${CERTBOT_HOST}
    volumes:
      - certificates:/etc/letsencrypt:rw
    command: 
      - 'certonly'
      - '--standalone'
      - '--agree-tos'
      - '-m gomesjm@ita.br'
      - '-n'
      - '-d ${CERT_DOMAINS}'
