#!/usr/bin/env bash
set -euo pipefail

function backup_postgres() {

    docker exec -i $1 /usr/bin/pg_dumpall -U postgres -w > .$1_temp.sql | gzip -9 > .$1_`date +%F-%H%M`.sql.gz
    rm .$1_temp.sql

}

backup_postgres postgres
backup_postgres postgres01
backup_postgres postgres02
