#!/usr/bin/env bash
set -euo pipefail

docker exec -i postgres /usr/bin/pg_dumpall -U postgres -w > .postgres-`date +%F-%H%M`.sql
docker exec -i postgres /usr/bin/pg_dumpall -U postgres -w > .postgres01-`date +%F-%H%M`.sql
docker exec -i postgres /usr/bin/pg_dumpall -U postgres -w > .postgres02-`date +%F-%H%M`.sql
