#!/usr/bin/env bash
set -euo pipefail

function backup_container {

    docker export $c | gzip --fast > ~/shared/in/tst/bkp/bkp_$1_$(date +%F-%H%M).docker.gz

}

function backup_postgres() {

    docker exec -i $1 /usr/bin/pg_dumpall -U postgres -w | gzip --fast > ~/shared/in/tst/bkp/bkp_$1_$(date +%F-%H%M).postgres.gz

}

function backup_mariadb() {

    docker exec -i $1 /usr/bin/mysqldump -u root -A | gzip --fast > ~/shared/in/tst/bkp/bkp_$1_$(date +%F-%H%M).mariadb.gz

}

function backup_mongodb() {

    docker exec -i $1 /usr/bin/mongodump --config=/etc/mongo/.mdbpass --gzip --archive=$1.tar
    TEMPFILE=`mktemp` && {
        docker cp $1:/$1.tar $TEMPFILE.tar
        docker exec -i $1 rm $1.tar
        gzip --fast $TEMPFILE.tar
        mv $TEMPFILE.tar.gz ~/shared/in/tst/bkp/bkp_$1_$(date +%F-%H%M).mongodb.gz
        rm -f $TEMPFILE
    }

}

for c in $(docker ps -a --format '{{.Names}}');
do
    backup_container $c
done

backup_postgres postgres
backup_postgres postgres01
backup_postgres postgres02

backup_mariadb mariadb01
backup_mariadb mariadb02

backup_mongodb mongodb
