address: 0.0.0.0:7373

admin:
  identity: disabled
   
tls:
  key: /root/.kes/certs/private.key
  cert: /root/.kes/certs/public.crt

keystore:
  fs:
    path: ./keys
  vault:
    endpoint: http://vault:8200
    engine: "kv/"
    version: "v2"
    approle:
      id: "fa8a2777-a2b3-d4c7-0240-66d805daf3b9"
      secret: "0a32856c-9fef-4f4d-0a64-52d5faf5fccb"
      retry: 15s
    status:
      ping: 10s

log:
  error: on
  audit: on 