address: 0.0.0.0:7373

admin:
  identity: disabled
   
tls:
  key: private.key
  cert: public.crt
   
policy:
  my-app: 
    allow:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*      
    - /v1/key/delete/*
    - /v1/key/list/*
    - /v1/identity/list/*
    identities:
    - f829b905ac119229bc75a60eab4fa9172f3cbba179df0b5601f8ed8168b9a9d5 # Use the identity of your API key
   
keystore:
  fs:
    path: ./keys

log:
  error: on
  audit: on 