address: 0.0.0.0:7373

admin:
  identity: disabled
   
tls:
  key: /root/.kes/certs/private.key
  cert: /root/.kes/certs/public.crt
   
policy:
  my-app: 
    allow:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*      
    - /v1/key/delete/*
    - /v1/key/list/*
    - /v1/identity/list/*
    identities:
    - 3df7e58699084d9e25b24e29e0028086a3f849b350a2d59797604e819a602d34
   
keystore:
  fs:
    path: ./keys

log:
  error: on
  audit: on 