services:

  memcached:
    container_name: memcached
    image: memcached:alpine
    restart: unless-stopped
    ports:
      - '11211:11211'
    networks:
      netlab01:
        ipv4_address: ${MEMCACHED_HOST}
    volumes:
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
