- name: Deploy Redmine container
  hosts: '{{target_inventory}}'
  become: yes
  become_user: gpes
  remote_user: gpes

  tasks:

    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: builddir

    - name: Copy project sources
      ansible.posix.synchronize:
        src: ./
        dest: "{{builddir.path}}"
        recursive: yes

    - name: Build project container (debug)
      community.docker.docker_compose:
        project_name: redmine
        project_src: "{{builddir.path}}"
        files:
          - "stack.yaml"
        build: true

    - name: Remove the temporary directory
      ansible.builtin.file:
        path: "{{builddir.path}}"
        state: absent
      when: builddir.path is defined
