- name: Deploy Redmine container
  hosts: '{{target_inventory}}'
  become: yes
  become_user: gpes
  remote_user: gpes

  tasks:

    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: builddir

    - name: Copy project sources
      ansible.posix.synchronize:
        src: ./
        dest: "{{builddir.path}}"
        recursive: yes

    - name: Build project container
      community.docker.docker_compose:
        project_name: redmine
        definition:
          services:

            redmine:
              container_name: redmine
              image: labqs/redmine:latest
              build:
                context: "{{builddir.path}}"
                dockerfile: Dockerfile.redmine
                target: redminebase
              restart: unless-stopped
              expose:
                - '3000'
              networks:
                - netlab01
              volumes:
                - $PWD/config/config.ru:/usr/src/redmine/config.ru
                - $PWD/config/configuration.yml:/usr/src/redmine/config/configuration.yml
                - redminedata:/usr/src/redmine/files
                - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
                - /etc/timezone:/etc/timezone:ro
                - /etc/localtime:/etc/localtime:ro
              environment:
                REDMINE_DB_POSTGRES: ${POSTGRES_HOST}
                REDMINE_DB_DATABASE: ${POSTGRES_DB}
                REDMINE_DB_USERNAME: ${POSTGRES_USR}
                REDMINE_DB_PASSWORD: ${POSTGRES_PWD}
                RAILS_RELATIVE_URL_ROOT: /redmine
              labels:
                - traefik.enable=true
                - traefik.http.routers.redmine.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/redmine`)
                - traefik.http.routers.redmine.tls=true
                - traefik.http.services.redmine.loadbalancer.server.port=3000
              command: 
                - 'envconsul'
                - '-upcase'
                - '-consul-addr=consul:8500'
                - '-prefix=labqs/redmine'
                - '-prefix=labqs/postgres'
                - '/usr/local/bin/ruby bin/rails server -b 0.0.0.0'

          volumes:
            redminedata:
              name: redminedata
              external: true

          networks:
            netlab01:
              external: true
        build: true

    - name: Remove the temporary directory
      ansible.builtin.file:
        path: "{{builddir.path}}"
        state: absent
      when: builddir.path is defined
