services:

  redmine:
    container_name: redmine
    image: labqs/redmine:latest
    build:
      context: .
      dockerfile: Dockerfile.redmine
      target: redminebase
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - netlab01
    volumes:
      - $PWD/config/config.ru:/usr/src/redmine/config.ru
      - $PWD/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - redminedata:/usr/src/redmine/files
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      RAILS_RELATIVE_URL_ROOT: /redmine
      CONSUL_TOKEN: 6b8a9882-1f79-699e-46b0-e01ff87cec1a
    labels:
      - traefik.enable=true
      - traefik.http.routers.redmine.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/redmine`)
      - traefik.http.routers.redmine.tls=true
      - traefik.http.services.redmine.loadbalancer.server.port=3000

volumes:
  redminedata:
    name: redminedata
    external: true

networks:
  netlab01:
    external: true
