services:

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      netlab01:
        ipv4_address: ${PROMETHEUS_HOST}
    volumes:
      - prometheusdata:/opt/bitnami/prometheus/data
      - $PWD/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  prometheusdata:
    name: prometheusdata
    driver: local
    driver_opts:
      type: none
      device: /home/gpes/VOLUMES/docker/volumes/prometheusdata/_data
      o: bind
