services:

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      netlab01:
        ipv4_address: ${PROMETHEUS_HOST}
    volumes:
      - $PWD/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/prometheus`)
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.middlewares.prometheus-stripprefix.stripprefix.prefixes=/prometheus
      - traefik.http.middlewares.prometheus-stripprefix.stripprefix.forceSlash=true
      - traefik.http.routers.prometheus.middlewares=prometheus-stripprefix@docker
    command:
      - '--config.file=/opt/bitnami/prometheus/conf/prometheus.yml'
      - '--storage.tsdb.path=/opt/bitnami/prometheus/data'
      - '--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries'
      - '--web.console.templates=/opt/bitnami/prometheus/conf/consoles'
      - '--web.listen-address=${PROMETHEUS_HOST}:9090'
      - '--web.route-prefix=prometheus'
      - '--web.external-url=http://${LAB_DOMAIN}/prometheus'

networks:
  netlab01:
    external: true
