services:

  gitea:
    container_name: gitea
    image: gitea/gitea
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      netlab01:
        ipv4_address: ${GITEA_HOST}
    volumes:
      - giteadata:/data
      - $PWD/config/app.ini:/data/gitea/conf/app.ini
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: ${POSTGRES_PWD}
      GITEA__webhook__ALLOWED_HOST_LIST: ${DRONE_HOST}
      GITEA__ui.meta__AUTHOR: Laboratório de Testes de Software
      GITEA__ui.meta__DESCRIPTION: Instituto Tecnológico de Aeronáutica
      GITEA__ui.meta__KEYWORDS: git,ita,testes,teste de software,qualidade,segurança
      GITEA__service__DISABLE_REGISTRATION: 'true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/git`)
      - traefik.http.routers.gitea.tls=true
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.middlewares.gitea-stripprefix.stripprefix.prefixes=/git
      - traefik.http.routers.gitea.middlewares=gitea-stripprefix@docker

volumes:
  giteadata:
    name: giteadata
    external: true

networks:
  netlab01:
    external: true
