services:

  gitea:
    container_name: gitea
    image: gitea/gitea
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      netlab01:
        ipv4_address: ${GITEA_HOST}
    volumes:
      - giteadata:/data
      - /etc/zoneinfo:/etc/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${POSTGRES_PWD}
      - GITEA__server__ROOT_URL=http://${LAB_DOMAIN}/git
      - GITEA__ui.meta__AUTHOR=Laboratório de Testes de Software
      - GITEA__ui.meta__DESCRIPTION=Instituto Tecnológico de Aeronáutica
      - GITEA__ui.meta__KEYWORDS=git,ita,testes,teste de software,qualidade,segurança

volumes:
  giteadata:
    name: giteadata
    driver: local
