#!/usr/bin/env bash
set -euo pipefail

sudo groupadd -f mecita

# sudo usermod -a -G mecita gpes

# Professores SI-TIH
# sudo usermod -a -G mecita lineu

# Pesquisadores SI-TIH
# sudo usermod -a -G mecita louro
# sudo usermod -a -G mecita shigemura
# sudo usermod -a -G mecita lippi
# sudo usermod -a -G mecita max
# sudo usermod -a -G mecita gomes
# sudo usermod -a -G mecita vitor
# sudo usermod -a -G mecita marcelo
# sudo usermod -a -G mecita matheus

# Pesquisadores IA-PLN
# sudo usermod -a -G mecita carvalho
# sudo usermod -a -G mecita rodrigues
# sudo usermod -a -G mecita ribeiro
# sudo usermod -a -G mecita silva
