services:

  redis:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    ports:
      - '10000:10000'
    networks:
      netlab01:
        ipv4_address: ${TRAEFIK_HOST}
    volumes:
      - $PWD/config/traefik.yml:/etc/traefik/traefik.yml
      - $PWD/config/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  netlab01:
    external: true
