services:

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      netlab01:
        ipv4_address: ${TRAEFIK_HOST}
    dns:
      - consul:8600
    volumes:
      - $PWD/config:/etc/traefik
      - traefikdata:/data
      - certificates:/usr/local/apache2/certificates:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  netlab01:
    external: true

volumes:
  traefikdata:
    name: traefikdata
    external: true
