services:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    expose:
      - '3001'
    networks:
      - netlab01
    volumes:
      - $PWD/config/grafana.ini:/etc/grafana/grafana.ini
      - $PWD/config/provisioning:/etc/grafana/provisioning
      - $PWD/config/dashboards:/var/lib/grafana/dashboards
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/grafana`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3001
      - traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana
      - traefik.http.middlewares.grafana-stripprefix.stripprefix.forceSlash=true
      - traefik.http.routers.grafana.middlewares=grafana-stripprefix@docker

networks:
  netlab01:
    external: true
