services:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - '3001:3001'
    networks:
      netlab01:
        ipv4_address: ${PROMETHEUS_HOST}
    volumes:
    volumes:
      - $PWD/config/grafana.ini:/etc/grafana/grafana.ini
      - $PWD/config/provisioning:/etc/grafana/provisioning
      - $PWD/config/dashboards:/var/lib/grafana/dashboards
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
