services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - '8083:80'
    networks:
      netlab01:
        ipv4_address: ${NEXTCLOUD_HOST}
    volumes:
      - nextclouddata:/var/www/html
      - flualfadata:/var/www/flualfa:ro
      - /home/gpes/shared/out:/var/www/shared:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PWD}
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_HOST: postgres
      NEXTCLOUD_ADMIN_USER: maint
      NEXTCLOUD_ADMIN_PASSWORD: ${SVC_PWD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${LAB_DOMAIN} ${CI_LAB_DOMAIN} ${CM_LAB_DOMAIN} {$IA_LAB_DOMAIN} ${ST_LAB_DOMAIN}
      OVERWRITEPROTOCOL: https
      OVERWRITEWEBROOT: nextcloud

volumes:
  nextclouddata:
    name: nextclouddata
    external: true
  flualfadata:
    name: flualfadata
    external: true

networks:
  netlab01:
    external: true
