services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud:fpm
    restart: unless-stopped
    ports:
      - '9000:9000'
    networks:
      netlab01:
        ipv4_address: ${NEXTCLOUD_HOST}
    volumes:
      - nextclouddata:/var/www/html
      - ${PWD}/apps:/var/www/html/custom_apps
      - ${PWD}/config:/var/www/html/config
      - ${PWD}/themes:/var/www/html/themes
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_HOST=postgres:5432

volumes:
  nextclouddata:
    name: nextclouddata
    driver: local
