[accessLog]
  filePath = "/var/log/access.log"

[http.middlewares.simpleAuth.basicAuth]
  users = [
    "@SVC_KEY"
  ]

[http.routers.api]
  rule = "Host(`@SVC_HOST`) && PathPrefix(`/api`, `/dashboard`, `/consul`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certresolver = "le"

[[tls.certificates]]
  certFile = "/usr/local/apache2/certificates/live/@CI_LAB_DOMAIN/fullchain.pem"
  keyFile = "/usr/local/apache2/certificates/live/@CI_LAB_DOMAIN/privkey.pem"
    
[[tls.certificates]]
  certFile = "/usr/local/apache2/certificates/live/@CM_LAB_DOMAIN/fullchain.pem"
  keyFile = "/usr/local/apache2/certificates/live/@CM_LAB_DOMAIN/privkey.pem"
    
[[tls.certificates]]
  certFile = "/usr/local/apache2/certificates/live/@ST_LAB_DOMAIN/fullchain.pem"
  keyFile = "/usr/local/apache2/certificates/live/@ST_LAB_DOMAIN/privkey.pem"
    
[[tls.certificates]]
  certFile = "/usr/local/apache2/certificates/live/@ST_C_LAB_DOMAIN/fullchain.pem"
  keyFile = "/usr/local/apache2/certificates/live/@ST_C_LAB_DOMAIN/privkey.pem"
    
[[tls.certificates]]
  certFile = "/usr/local/apache2/certificates/live/@SVC_HOST/fullchain.pem"
  keyFile = "/usr/local/apache2/certificates/live/@SVC_HOST/privkey.pem"
