[http.middlewares.simpleAuth.basicAuth]
  users = [
    "@SVC_KEY"
  ]

[http.routers.api]
  rule = "Host(`@SVC_HOST`) && PathPrefix(`/api`, `/dashboard`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certresolver = "le"
