[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.le.acme]
  email = "labqs@ita.br"
  storage = "/data/acme.json"
  [certificatesResolvers.le.acme.tlsChallenge]

[providers.docker]
  exposedByDefault = false
  watch = true
  network = "netlab01"

[providers.consulCatalog]
  prefix = "labqs"
  defaultRule = "Host(`{{ .Name }}`.{{ index .Labels \"customLabel\"}}`)"
  watch = true
  [providers.consulCatalog.endpoint]
      address = "consul:8500"
      scheme = "http"
      datacenter = "labqs"

[providers.file]
  filename = "/etc/traefik/dynamic.toml"
