[http.middlewares.simpleAuth.basicAuth]
  users = [
    "@SVC_KEY"
  ]

[http.routers.api]
  rule = "Host(`test.labqs.ita.br`) && PathPrefix(`/api`, `/dashboard`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
