[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.le.acme]
  email = "labqs@ita.br"
  storage = "/data/acme.json"
  [certificatesResolvers.le.acme.tlsChallenge]

[providers.docker]
  exposedByDefault = false
  watch = true
  network = "netlab01"

[providers.consulCatalog]
  defaultRule = "Host(`{{ .Name }}.consul.labqs.tech`)"
  [providers.consulCatalog.endpoint]
      address = "consul:8500"
      scheme = "http"
      token = "b7fbf73e-570e-4322-bf40-421fe308d7e9"

[providers.consul]
  endpoints = ["consul:8500"]
  token = "b7fbf73e-570e-4322-bf40-421fe308d7e9"

[providers.file]
  filename = "/etc/traefik/dynamic.toml"
