[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.le.acme]
  email = "labqs@ita.br"
  storage = "/data/acme.json"
  [certificatesResolvers.le.acme.tlsChallenge]

[providers.docker]
  exposedByDefault = false
  watch = true
  network = "netlab01"

[providers.consulCatalog]
  prefix = "labqs"
  defaultRule = "Host(` .Name `) && PathPrefix(`/consul`)"
  [providers.consulCatalog.endpoint]
      address = "consul:8500"
      scheme = "http"
      token = "150d947c-9383-78fe-31ee-b986774fdba2"

[providers.consul]
  endpoints = ["consul:8500"]
  token = "150d947c-9383-78fe-31ee-b986774fdba2"

[providers.file]
  filename = "/etc/traefik/dynamic.toml"
