#!/usr/bin/env bash
set -euo pipefail

docker cp rabbitmng:/var/lib/rabbitmq/.erlang.cookie .erlang.cookie
docker cp .erlang.cookie rabbitmq01:/var/lib/rabbitmq/.erlang.cookie
docker cp .erlang.cookie rabbitmq02:/var/lib/rabbitmq/.erlang.cookie

docker restart rabbitmq01 rabbitmq02

docker exec rabbitmq01 rabbitmqctl -n rabbitmq01@rabbitmq01 stop_app
docker exec rabbitmq01 rabbitmqctl -n rabbitmq01@rabbitmq01 reset
docker exec rabbitmq01 rabbitmqctl -n rabbitmq01@rabbitmq01 join_cluster rabbitmng@rabbitmng
docker exec rabbitmq01 rabbitmqctl -n rabbitmq01@rabbitmq01 start_app

docker exec rabbitmq02 rabbitmqctl -n rabbitmq02@rabbitmq02 stop_app
docker exec rabbitmq02 rabbitmqctl -n rabbitmq02@rabbitmq02 reset
docker exec rabbitmq02 rabbitmqctl -n rabbitmq02@rabbitmq02 join_cluster rabbitmng@rabbitmng
docker exec rabbitmq02 rabbitmqctl -n rabbitmq02@rabbitmq02 start_app
