services:

  rabbitmng:
    container_name: rabbitmng
    hostname: rabbitmng
    image: rabbitmq:management-alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - ':15672'
      - ':5672'
    networks:
      - netlab01
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - $PWD/config/rabbitmng/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
      - $PWD/config/rabbitmng/20-user.conf:/etc/rabbitmq/conf.d/20-user.conf:ro
      - $PWD/config/rabbitmng/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      RABBITMQ_CONF_ENV_FILE: /etc/rabbitmq/rabbitmq-env.conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmng.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/rabbitmng`)
      - traefik.http.routers.rabbitmng.tls=true
      - traefik.http.services.rabbitmng.loadbalancer.server.port=15672
      - traefik.http.middlewares.rabbitmng-stripprefix.stripprefix.prefixes=/rabbitmng
      - traefik.http.middlewares.rabbitmng-stripprefix.stripprefix.forceSlash=true
      - traefik.http.routers.rabbitmng.middlewares=rabbitmng-stripprefix@docker
      - SERVICE_4369_NAME=rabbitmng
      - SERVICE_5671_NAME=rabbitmng
      - SERVICE_5672_NAME=rabbitmng
      - SERVICE_15671_NAME=rabbitmng
      - SERVICE_15672_NAME=rabbitmng
      - SERVICE_15691_NAME=rabbitmng
      - SERVICE_15692_NAME=rabbitmng
      - SERVICE_25672_NAME=rabbotmng

  rabbitmq01:
    container_name: rabbitmq01
    hostname: rabbitmq01
    image: rabbitmq:alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - netlab01
    volumes:
      - rabbitmqdata01:/var/lib/rabbitmq
      - $PWD/config/rabbitmq01/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
      - $PWD/config/rabbitmq01/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      RABBITMQ_CONF_ENV_FILE: /etc/rabbitmq/rabbitmq-env.conf
    labels:
      - SERVICE_4369_NAME=rabbitmq01
      - SERVICE_5671_NAME=rabbitmq01
      - SERVICE_5672_NAME=rabbitmq01
      - SERVICE_15671_NAME=rabbitmq01
      - SERVICE_15672_NAME=rabbitmq01
      - SERVICE_15691_NAME=rabbitmq01
      - SERVICE_15692_NAME=rabbitmq01
      - SERVICE_25672_NAME=rabbitmq01

  rabbitmq02:
    container_name: rabbitmq02
    hostname: rabbitmq02
    image: rabbitmq:alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - netlab01
    volumes:
      - rabbitmqdata02:/var/lib/rabbitmq
      - $PWD/config/rabbitmq02/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
      - $PWD/config/rabbitmq02/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      RABBITMQ_CONF_ENV_FILE: /etc/rabbitmq/rabbitmq-env.conf
    labels:
      - SERVICE_4369_NAME=rabbitmq02
      - SERVICE_5671_NAME=rabbitmq02
      - SERVICE_5672_NAME=rabbitmq02
      - SERVICE_15671_NAME=rabbitmq02
      - SERVICE_15672_NAME=rabbitmq02
      - SERVICE_15691_NAME=rabbitmq02
      - SERVICE_15692_NAME=rabbitmq02
      - SERVICE_25672_NAME=rabbitmq02

volumes:
  rabbitmqdata:
    name: rabbitmqdata
    external: true
  rabbitmqdata01:
    name: rabbitmqdata01
    external: true
  rabbitmqdata02:
    name: rabbitmqdata02
    external: true

networks:
  netlab01:
    external: true
