services:

  rabbitmq01:
    container_name: rabbitmq01
    image: rabbitmq:alpine
    restart: unless-stopped
    networks:
      netlab01:
        ipv4_address: ${RABBITMQ_HOST01}
    volumes:
      - $PWD/config/rabbitmq01/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  rabbitmq02:
    container_name: rabbitmq02
    image: rabbitmq:alpine
    restart: unless-stopped
    networks:
      netlab01:
        ipv4_address: ${RABBITMQ_HOST02}
    volumes:
      - $PWD/config/rabbitmq02/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  rabbitmng:
    container_name: rabbitmng
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports:
      - '15672:15672'
    networks:
      netlab01:
        ipv4_address: ${RABBITMQ_HOST}
    volumes:
      - $PWD/config/rabbitmng/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - $PWD/config/rabbitmng/20-user.conf:/etc/rabbitmq/conf.d/20-user.conf:ro
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
