services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    restart: unless-stopped
    networks:
      netlab01:
        ipv4_address: ${RABBITMQ_HOST01}
    volumes:
      - $PWD/config:/etc/rabbitmq/conf.d:ro
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  rabbitmng:
    container_name: rabbitmng
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports:
      - '15672:15672'
    networks:
      netlab01:
        ipv4_address: ${RABBITMQ_HOST}
    volumes:
      # - $PWD/config:/etc/rabbitmq/conf.d:ro
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
