FROM tensorflow/tensorflow:latest

#set up environment
COPY app/requirements_tensor.txt /app/requirements_tensor.txt
RUN pip3 install -r /app/requirements_tensor.txt

#copies the applicaiton from local path to container path
COPY app/ /app/
WORKDIR /app

CMD ["python3", "tensor_test_driver.py"]
