ARG OWNER=labqs
ARG BASE_CONTAINER=$OWNER/tensorflow-notebook
FROM $BASE_CONTAINER AS jupyterlabbase

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# JavaScript/R pre-requisites
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    software-properties-common \
    libzmq3-dev \
    nodejs \
    npm \
    fonts-dejavu \
    unixodbc \
    unixodbc-dev \
    r-cran-rodbc \
    gfortran \
    gcc \
    git-lfs \
    nvidia-cuda-toolkit \
    apt-transport-https \
    # OpenJDK 11 is installed as a dependecy for PySpark
    openjdk-11-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN npm install -g ijavascript && \
    ijsinstall

# R packages including IRKernel which gets installed globally.
# r-e1071: dependency of the caret R package
# Git
RUN mamba install --quiet --yes \
    'jupyterlab-git' \
    'r-base' \
    'r-caret' \
    'r-crayon' \
    'r-devtools' \
    'r-e1071' \
    'r-forecast' \
    'r-hexbin' \
    'r-htmltools' \
    'r-htmlwidgets' \
    'r-irkernel' \
    'r-nycflights13' \
    'r-randomforest' \
    'r-rcurl' \
    'r-rmarkdown' \
    'r-rodbc' \
    'r-rsqlite' \
    'r-shiny' \
    'r-tidyverse' \
    'unixodbc' \
    'r-tidymodels' \ 
    'python-decouple' \
    'webdav4' \
    'psycopg2' \
    'sshtunnel' \
    'texinfo' \
    'pyspark' \
    'boto3' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# CUDA 12.4 compatibility
RUN pip3 install \
    'torch' \
    'torchvision' \
    'torchaudio' \
    --index-url 'https://download.pytorch.org/whl/cu124' && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN mamba install --quiet --yes -c \
    'conda-forge/label/gcc7'  \
    'xeus-cling' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Julia dependencies
# install Julia packages in /opt/julia instead of ${HOME}
ENV JULIA_DEPOT_PATH=/opt/julia \
    JULIA_PKGDIR=/opt/julia

# Setup Julia
RUN /opt/setup-scripts/setup-julia.bash

# Setup IJulia kernel & other packages
RUN /opt/setup-scripts/setup-julia-packages.bash

# Setup IJava kernel
RUN wget https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip && \
    unzip ijava-1.3.0.zip && \
    python3 install.py

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

USER ${NB_UID}
