ARG OWNER=labqs
ARG BASE_CONTAINER=$OWNER/minimal-notebook-cuda12
FROM $BASE_CONTAINER AS jupyterfabbase

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

USER ${NB_UID}
