services:

  foundation:
    build:
      context: ./stacks/docker-stacks-foundation
    image: labqs/docker-stacks-foundation:latest

  base:
    build:
      context: ./stacks/base-notebook
    image: labqs/base-notebook:latest

  minimal:
    build: 
      context: ./stacks/minimal-notebook
    image: labqs/minimal-notebook:latest

  scipy:
    build: 
      context: ./stacks/scipy-notebook
    image: labqs/scipy-notebook:latest

  tensorflow:
    build: 
      context: ./stacks/tensorflow-notebook
    image: labqs/tensorflow-notebook:latest

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
      target: jupyterlabbase
    image: labqs/jupyterlab:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  jupyterhub:
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      target: jupyterhubbase
      args:
      - GPES_PASSWORD=${SVC_PWD}
      - GPES_DEV_PASSWORD=${SVC_DEV_PWD}
    image: labqs/jupyterhub:latest
    restart: unless-stopped
    ports:
      - '8000:8000'
    networks:
      netlab01:
        ipv4_address: ${JUPYTER_HOST}
    volumes:
      - $PWD/config/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py:ro
      - jupyterdata:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_JUPYTER_CONTAINER: jupyter
      DOCKER_NETWORK_NAME: netlab01
      DOCKER_NOTEBOOK_IMAGE:  labqs/jupyterlab:latest
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      DOCKER_SPAWN_CMD: start-singleuser.sh

    command: [ "jupyterhub", "-f", "/etc/jupyterhub/jupyterhub_config.py" ]

volumes:
  jupyterdata:
    name: jupyterdata
    external: true

networks:
  netlab01:
    external: true
