services:

  jupyter:
    container_name: jupyter
    image: jupyter/datascience-notebook
    restart: unless-stopped
    ports:
      - '8888:80'
    networks:
      netlab01:
        ipv4_address: ${JUPYTER_HOST}
    volumes:
      - jupyterdata:/home/jovyan/work
      - $PWD/config:/home/jovyan/.jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: [ "start-notebook.sh", "--NotebookApp.token=${SVC_TOKEN}"]

volumes:
  jupyterdata:
    name: jupyterdata
    driver: local
