#!/usr/bin/env bash
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
   echo "Executar como root" 1>&2
   exit 1
fi

read -p "Tem certeza? " -n 1 -r
if [[ $REPLY =~ ^[Ss]$ ]]
then
    docker run --rm --tty --interactive \
        --name gitlab-runner-register \
        --add-host "gitlab:172.1.1.10" \
        --link=gitlab \
        --network="netlab01" \
        --volume $PWD/runner01:/etc/gitlab-runner \
        gitlab/gitlab-runner:alpine \
            register \
                --non-interactive \
                --executor "docker" \
                --url "http://192.168.15.201:8002/" \
                --registration-token "gRETJxmpoCdrgEtARPqQCsAnJjB91uIpaj6eaDepY74=" \
                --description "docker-runner" \
                --tag-list "docker" \
                --run-untagged \
                --locked="false"
fi
