services:

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    ports:
      - '${SERVER_HOST}:8022:22'
      - '${SERVER_HOST}:8002:80'
      - '${SERVER_HOST}:8443:443'
    networks:
      - netlab01
    volumes:
      - $PWD/config:/etc/gitlab
      - gitlablogs:/var/log/gitlab
      - gitlabdata:/var/opt/gitlab
      - gitlabback:/var/opt/gitlab/backups
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://localhost/gitlab/"
        letsencrypt['enable'] = false
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "${POSTGRES_PWD}"
        gitlab_rails['db_host'] = "postgres"
        gitlab_rails['db_database'] = "gitlab"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        gitlab_rails['redis_password'] = '${REDIS_PWD}'

  runner:
    container_name: runner01
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - $PWD/runner01:/etc/gitlab-runner
    networks:
      - netlab01

volumes:
  gitlablogs:
    name: gitlablogs
    driver: local
  gitlabdata:
    name: gitlabdata
    driver: local
  gitlabback:
    name: gitlabback
    driver: local
