services:

  mongodb:
    container_name: mongodb
    image: mongo:4.4.14-focal
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo ${MONGODB_HOST}:27017/local --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    ports:
      - '27020:27017'
    networks:
      netlab01:
        ipv4_address: ${MONGODB_HOST}
    volumes:
      - mongodata:/data/db:rw
      - $PWD/mongodb/config/custom.conf:/etc/mongo/custom.conf
      - $PWD/mongodb/config/.mdbpass:/etc/mongo/.mdbpass
      - $PWD/mongodb/init:/docker-entrypoint-initdb.d:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${SVC_PWD}
    command: --config /etc/mongo/custom.conf

volumes:
  mongodata:
    name: mongodata
    external: true

networks:
  netlab01:
    external: true
