#!/usr/bin/env bash
set -euo pipefail


mkdir -p /export
mkdir -p /import
mkdir -p /replica

if [[ $# -ne 1 && $# -ne 2 ]]; then

    echo "Informe [ dev | tst | hom ]"

    exit 1

elif [ "$1" == "tst" ]; then

    # Servidor do lab
    echo "tst.labqs" > /export/lab
    
elif [ "$1" == "dev" ]; then

    # Servidores de desenvolvimento e testes
    echo "dev.labqs" > /export/lab

elif [ "$1" == "hom" ]; then

    # Servidores de homologação
    echo "hom.labqs" > /export/lab

else

    echo "Argumento $1 incorreto. Use [ dev | tst | hom ]"

    exit 1

fi

exit 0
