services:

  juice:
    container_name: juice
    image: juicelabs/server:2022-12-23-2154-7c6e2773-ubuntu-20
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - '43210:43210'
    networks:
      netlab01:
        ipv4_address: ${JUICE_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  netlab01:
    external: true
