services:

  dispatcher:
    image: diffgram/local_dispatcher:latest
    ports:
    - "0.0.0.0:8085:8085"
    expose: [8085]
    depends_on:
    - frontend
    - default
    - walrus
    environment:
      SAME_HOST: ${SAME_HOST}
  frontend:
    image: diffgram/frontend:latest
    ports:
    - "0.0.0.0:8081:80"
    expose: [80]
    depends_on:
    - default
  eventhandlers:
    image: diffgram/eventhandlers:latest
    ports:
    - "0.0.0.0:8086:8086"
    expose: [8086]
    depends_on:
      default:
        condition: service_started
    volumes:
    - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
    env_file:
      - .env
    environment:
      PYTHONPATH: "/app/"
      DIFFGRAM_SERVICE_NAME: eventhandlers
    entrypoint: ["python3", "-u", "/app/main.py"]

  walrus:
    image: diffgram/walrus:latest
    ports:
    - "0.0.0.0:8082:8082"
    expose: [8082]
    depends_on:
      default:
        condition: service_started
    volumes:
    - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
    env_file:
      - .env
    environment:
      PYTHONPATH: "/app/"
      DIFFGRAM_SERVICE_NAME: walrus
    entrypoint: ["python3", "-u", "/app/main.py"]

  default:
    image: diffgram/default:latest
    healthcheck:
      test: curl --fail http://default:8080/api/status || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 80s
    ports:
    - "0.0.0.0:8080:8080"
    expose: [8080]
    depends_on:
      db_migration:
        condition: service_completed_successfully
    volumes:
    - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
    env_file:
      - .env
    environment:
      PYTHONPATH: "/app/"
      DIFFGRAM_SERVICE_NAME: default
    command: ["python3", "-u", "/app/main.py"]

  db_migration:
    image: diffgram/default:latest
    env_file:
      - .env
    environment:
      PYTHONPATH: "/app/"
    command: ["/app/db-init.sh", "${DATABASE_HOST}"]
    depends_on:
      db:
        condition: service_healthy

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose: [9000, 9001]
    volumes:
      - ./test/.minio/data:/export
      - ./test/.minio/config:/root/.minio
    environment:
      - "MINIO_ROOT_USER=${DIFFGRAM_MINIO_ACCESS_KEY_ID}"
      - "MINIO_ROOT_PASSWORD=${DIFFGRAM_MINIO_ACCESS_KEY_SECRET}"
    command: server /export --console-address :9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${DIFFGRAM_MINIO_ACCESS_KEY_ID} ${DIFFGRAM_MINIO_ACCESS_KEY_SECRET};
      /usr/bin/mc mb myminio/${DIFFGRAM_S3_BUCKET_NAME};
      /usr/bin/mc policy set policy myminio/${DIFFGRAM_S3_BUCKET_NAME} ;
      exit 0;
      "

volumes:
  static: {}