services:

  consul_agent:
    container_name: consul_agent
    image: hashicorp/consul:latest
    restart: unless-stopped
    networks:
      - netlab01
    volumes:
      - $PWD/config/consul/agent.json:/consul/config/agent.json:ro
      - $PWD/config/consul/acl:/consul/acl:ro
      - consulagentdata:/consul/data:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_HTTP_TOKEN=5fdbf566-22f2-73e2-2525-9eaf6ad8d781
    command:
      - agent

volumes:
  consulagentdata:
    name: consulagentdata
    external: true

networks:
  netlab01:
    external: true
