services:

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    restart: unless-stopped
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - CONSUL_HTTP_TOKEN=38f2c223-16b5-7145-0a8e-095f8a22a739
    command: 
      - "-cleanup=true"
      - "-deregister=always"
      - "-resync=10"
      - "-internal"
      - "consul://consul:8500"

networks:
  netlab01:
    external: true
