services:

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    restart: unless-stopped
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: 
      - "-cleanup=true"
      - "-deregister=always"
      - "-resync=10"
      - "-internal"
      - "consul://consul:8500"

networks:
  netlab01:
    external: true
