services:

  registrator:
    container_name: registrator
    image: metabrainz/serviceregistrator:latest
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --ip 127.0.0.1
      - --consul-port 8500
      - --consul-host consul

networks:
  netlab01:
    external: true
