services:

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: 
      - "-cleanup=true"
      - "-deregister=always"
      - "-resync=10"
      - "-tags=labqs"
      - "-ip=161.24.23.94"
      - "consul://consul:8500"

networks:
  netlab01:
    external: true
