services:

  registrator:
    container_name: registrator
    image: metabrainz/serviceregistrator:latest
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - -i 127.0.0.1
      - -h consul
      - -p 8500

networks:
  netlab01:
    external: true
