services:

  registrator:
    container_name: registrator
    image: hypolas/registrator:latest
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: 
      - "-internal"
      - "-cleanup"
      - "-resync=10"
      - "consul://consul:8500"

networks:
  netlab01:
    external: true
