services:

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: 
      - "-cleanup=true"
      - "-deregister=always"
      - "-resync=10"

networks:
  netlab01:
    external: true
