services:

  vault:
    container_name: vault
    image: vault:1.13.3
    restart: unless-stopped
    ports:
      - '8200:8200'
    networks:
      netlab01:
        ipv4_address: ${VAULT_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VAULT_NAMESPACE: "admin"
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "${SVC_PWD}"
      VAULT_TOKEN: "${SVC_PWD}"

networks:
  netlab01:
    external: true
