services:

  vault:
    container_name: vault
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    ports:
      - '8200:8200'
      - '8201:8201'
    networks:
      netlab01:
        ipv4_address: ${VAULT_HOST}
    volumes:
      - $PWD/config:/vault/config:rw
      - vaultdata:/vault/file
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: server

networks:
  netlab01:
    external: true

volumes:
  vaultdata:
    name: vaultdata
    external: true
