services:

  consul:
    container_name: consul
    image: hashicorp/consul:latest
    restart: unless-stopped
    networks:
      netlab01:
        ipv4_address: ${CONSUL_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  vault:
    container_name: vault
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    ports:
      - '8200:8200'
    networks:
      netlab01:
        ipv4_address: ${VAULT_HOST}
    volumes:
      - $PWD/config:/vault/config:ro
      - vaultdata:/vault/file:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server

networks:
  netlab01:
    external: true

volumes:
  vaultdata:
    name: vaultdata
    external: true
