services:

  vault:
    container_name: vault
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    ports:
      - '8200:8200'
    networks:
      netlab01:
        ipv4_address: ${VAULT_HOST}
    volumes:
      - $PWD/config:/vault/config:ro
      - vaultdata:/vault/file:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=${SVC_PWD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/ui`)
      - traefik.http.routers.vault.tls=true
      - traefik.http.services.vault.loadbalancer.server.port=8200
    command: server

networks:
  netlab01:
    external: true

volumes:
  vaultdata:
    name: vaultdata
    external: true
