services:

  httpd:
    container_name: httpd
    image: httpd
    restart: unless-stopped
    ports:
      - '10000:80'
    networks:
      netlab01:
        ipv4_address: ${HTTPD_HOST}
    volumes:
      - $PWD/panel/static:/usr/local/apache2/htdocs:ro
      - $PWD/panel/config:/usr/local/apache2/conf:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      LAB_DOMAIN: ${LAB_DOMAIN}
      CI_LAB_DOMAIN: ${CI_LAB_DOMAIN}
      CM_LAB_DOMAIN: ${CM_LAB_DOMAIN}
      IA_LAB_DOMAIN: ${IA_LAB_DOMAIN}
      ST_LAB_DOMAIN: ${ST_LAB_DOMAIN}
      ST_C_LAB_DOMAIN: ${ST_C_LAB_DOMAIN}
    labels:
      - traefik.http.routers.httpd.rule=(Host(`${LAB_DOMAIN}`) && Path(`/assets`))
      - traefik.http.routers.httpd.tls=true
      - traefik.http.routers.httpd.tls.certresolver=le
      - traefik.http.services.httpd.loadbalancer.server.port=80
      - traefik.http.middlewares.httpd-stripprefix.stripprefix.prefixes=/assets
      - traefik.http.routers.httpd.middlewares=httpd-stripprefix@docker
networks:
  netlab01:
    external: true
