services:

  httpd:
    container_name: httpd
    image: httpd
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      netlab01:
        ipv4_address: ${HTTPD_HOST}
    volumes:
      - $PWD/panel/static:/usr/local/apache2/htdocs:ro
      - $PWD/panel/config:/usr/local/apache2/conf:ro
      - certificates:/usr/local/apache2/certificates:ro

  php:
    container_name: php
    image: php:7.4.30-apache
    restart: unless-stopped
    ports:
      - '9000:80'
    networks:
      netlab01:
        ipv4_address: ${PHP_HOST}
    volumes:
      - $PWD/php:/var/www/html:ro
    environment:
      - PHP_HOST=${LAB_DOMAIN}
    depends_on:
      - httpd
