#!/usr/bin/env bash
set -euo pipefail

source ./functions

if [[ $# -ne 2 ]]; then

    echo "Informe { dev | tst | hom | ia } nome do domínio"

    exit 1

else

    domain $1

fi

source ./config

cd ../certbot
echo '* Letsencrypt certbot *'

echo 'Certificar que apache está parado'
docker stop httpd || true

CERT_DOMAINS=$2
echo 'Registrando '${CERT_DOMAINS}

# Usando docker
echo "Verificar se está configurado para criação ou renovação"
# docker compose -f renew.yaml -f ../common/volumes.$1.yaml up --detach
# docker compose -f register.yaml -f ../common/volumes.$1.yaml up --detach
echo "$(tput setaf 1)Aguarde a finalização da execução$(tput sgr0)"
docker logs certbot --follow

# Usando letsencrypt
# sudo certbot certonly --standalone --agree-tos -m labqs@ita.br -n -d ${CERT_DOMAINS}
# sudo certbot renew --force-renewal

echo "$(tput setaf 1)Re-inicar apache com script setup $(1)$(tput sgr0)"
