#!/usr/bin/env bash
set -euo pipefail

source ./functions

# Para registrar 
# if [[ $# -ne 2 ]]; then
# Para renovar
if [[ $# -ne 1 ]]; then

    echo "Informe { dev | tst | hom | ia }"

    exit 1

else

    domain $1

fi

source ./config

cd ../certbot
echo '* Letsencrypt certbot *'

echo 'Certificar que apache está parado'
docker stop httpd || true

# Para registrar
# export CERT_DOMAINS=$2
# echo 'Registrando '${CERT_DOMAINS}

# Usando docker
echo "Verificar se está configurado para criação ou renovação"
# docker compose -f renew.yaml -f ../common/volumes.$1.yaml up --detach
# docker compose -f register.yaml -f ../common/volumes.$1.yaml up --detach
echo "$(tput setaf 1)Aguarde a finalização da execução$(tput sgr0)"
docker logs certbot --follow

echo "$(tput setaf 1)Re-inicar apache com script httpd $1$(tput sgr0)"
