#!/usr/bin/env bash
set -euo pipefail


source ./config


# cd ../certbot
# echo '* Letsencrypt certbot *'

# echo 'Certificar que apache está parado'
# docker stop httpd

# echo 'Registrando '${CERT_DOMAINS}
# # docker-compose -f stack.yaml -f ../common/use.yaml up --detach



# Servidor do lab
export LAB_DOMAIN=test.labqs.ita.br
export CI_LAB_DOMAIN=ci.test.labqs.ita.br

# Servidores de desenvolvimento e testes
# export LAB_DOMAIN=dev.labqs.ita.br
# export CI_LAB_DOMAIN=ci.labqs.ita.br

export CERT_DOMAINS=$LAB_DOMAIN,$CI_LAB_DOMAIN


cd ../httpd
echo '* Apache HTTPD *'

# echo 'Certificar que certbot está parado'
# docker stop certbot

echo "Registrar apache com domínios $(tput setaf 1)"$CERT_DOMAINS"$(tput sgr0)"

sed -i 's/@LAB_DOMAIN/'$LAB_DOMAIN'/g' panel/config/sites/000-default.conf
sed -i 's/@CI_LAB_DOMAIN/'$CI_LAB_DOMAIN'/g' panel/config/sites/001-ci.conf

sed -i 's/@CI_LAB_DOMAIN/'$CI_LAB_DOMAIN'/g' panel/static/index.html

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach --remove-orphans
# docker restart httpd

# cd ../locust
# echo '* Locust *'

# docker-compose -f stack.yaml -f ../common/use.yaml up --scale worker=2 --detach


# cd ../postgresql
# echo '* PostgreSQL *'

# echo 'SVC_PWD='$(openssl rand -hex 8) > .env
# echo 'SVC_PWD_01='$(openssl rand -hex 8) >> .env
# echo 'SVC_PWD_02='$(openssl rand -hex 8) >> .env

# echo 'localhost:5432:*:postgres:'$(awk -F'=' '$1 =="SVC_PWD" {print $2}' .env) > ./postgres/config/.pgpass
# chmod 0600 ./postgres/config/.pgpass
# echo 'localhost:5432:*:postgres:'$(awk -F'=' '$1 =="SVC_PWD_01" {print $2}' .env) > ./postgres01/config/.pgpass
# chmod 0600 ./postgres01/config/.pgpass
# echo 'localhost:5432:*:postgres:'$(awk -F'=' '$1 =="SVC_PWD_02" {print $2}' .env) > ./postgres02/config/.pgpass
# chmod 0600 ./postgres02/config/.pgpass

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach


# cd ../mongodb
# echo '* MongoDB *'

# echo 'SVC_PWD='$(openssl rand -hex 8) > .env
# echo 'SVC_PWD_01='$(openssl rand -hex 8) >> .env
# echo 'SVC_PWD_02='$(openssl rand -hex 8) >> .env

# echo 'uri: "mongodb://root:'$(awk -F'=' '$1 =="SVC_PWD" {print $2}' .env)'@localhost:27017"' > ./mongodb/config/.mdbpass
# chmod 0600 ./mongodb/config/.mdbpass
# echo 'uri: "mongodb://root:'$(awk -F'=' '$1 =="SVC_PWD_01" {print $2}' .env)'@localhost:27017"' > ./mongodb01/config/.mdbpass
# chmod 0600 ./mongodb01/config/.mdbpass
# echo 'uri: "mongodb://root:'$(awk -F'=' '$1 =="SVC_PWD_02" {print $2}' .env)'@localhost:27017"' > ./mongodb02/config/.mdbpass
# chmod 0600 ./mongodb02/config/.mdbpass

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach


# cd ../mariadb
# echo '* MariaDB *'

# echo 'SVC_PWD_01='$(openssl rand -hex 8) > .env
# echo 'SVC_PWD_02='$(openssl rand -hex 8) >> .env

# echo '[client]' > mariadb01/config/autologin.cnf
# echo 'user = root' >> mariadb01/config/autologin.cnf
# echo 'password = '$(awk -F'=' '$1 =="SVC_PWD_01" {print $2}' .env) >> mariadb01/config/autologin.cnf

# echo '[client]' > mariadb02/config/autologin.cnf
# echo 'user = root' >> mariadb02/config/autologin.cnf
# echo 'password = '$(awk -F'=' '$1 =="SVC_PWD_02" {print $2}' .env) >> mariadb02/config/autologin.cnf

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach


# cd ../redis
# echo '* Redis *'

# echo 'SVC_PWD='$(openssl rand -hex 8) > .env
# echo 'SVC_PWD_01='$(openssl rand -hex 8) >> .env
# echo 'SVC_PWD_02='$(openssl rand -hex 8) >> .env

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach


# cd ../adminer
# echo '* Adminer *'

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach


# cd ../nextcloud
# echo '* Nextcloud *'

# echo 'SVC_PWD='$(openssl rand -hex 8) > .env
# echo 'REDIS_PWD='$(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../redis/.env) >> .env
# echo 'POSTGRES_PWD='$(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../postgresql/.env) >> .env

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach


# cd ../gitea
# echo '* Gitea *'

# echo "Navegar até a página de configuração do serviço https://$LAB_DOMAIN/git"
# echo 'e definir a conta do administrador (no final da página, em "Optional Settings")'

# echo 'POSTGRES_PWD='$(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../postgresql/.env) > .env

# docker-compose -f stack.yaml -f ../common/use.yaml up --detach


# cd ../drone
# echo '* Drone *'

# echo "Gere uma aplicação OAuth no Gitea para o Drone em https://$LAB_DOMAIN/git"
# echo "com endereço de retorno https://$CI_LAB_DOMAIN/login"
# echo 'Após gerar a aplicação informe os dados abaixo'
# read -p 'Informe o "Client ID": ' GID
# read -p 'Informe o "Client Secret": ' GSCRT

# echo 'DRONE_TOKEN='$(openssl rand -hex 32) > .env
# echo 'POSTGRES_PWD='$(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../postgresql/.env) >> .env
# echo 'GITEA_ID='$GID >> .env
# echo 'GITEA_PWD='$GSCRT >> .env
# echo 'SVC_PWD='$(openssl rand -hex 16) >> .env

# docker-compose -f stack.yaml -f ../common/use.yaml up --scale docker=2 --scale ssh=2 --detach --remove-orphans


cd ../ansible
echo '* Ansible *'

docker-compose -f stack.yaml -f ../common/use.yaml up --build --detach
