#!/usr/bin/env bash
set -euo pipefail

source ./config

source ./functions

git checkout ../httpd/panel/config/sites/000-default.conf
git checkout ../httpd/panel/config/sites/001-ci.conf
git checkout ../httpd/panel/config/sites/002-cm.conf

cd ../traefik
git checkout config/traefik_dynamic.toml
sed -i 's\@SVC_KEY\'$(docker run --rm --entrypoint htpasswd httpd -nb admin $(awk -F'=' '$1 =="SVC_PWD" {print $2}' ./.env))'\g' config/traefik_dynamic.toml

cd ../rabbitmq
git checkout config/rabbitmng/20-user.conf
sed -i 's/@SVC_PWD/'$(awk -F'=' '$1 =="SVC_PWD" {print $2}' .env)'/g' config/rabbitmng/20-user.conf

cd ../registry
git checkout config/config.yml
sed -i 's/@LAB_DOMAIN/'$LAB_DOMAIN'/g' config/config.yml
sed -i 's/@REDIS_PWD/'$(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../redis/.env)'/g' config/config.yml

git pull


if [[ $# -ne 1 && $# -ne 2 ]]; then

    echo "Informe { dev | tst | hom | ia } [ config ]"

    exit 1

else

    domain $1

fi

git submodule update --init --recursive
