#!/usr/bin/env bash
set -euo pipefail


git checkout ../httpd/panel/config/sites/000-default.conf
git checkout ../httpd/panel/config/sites/001-ci.conf
git checkout ../httpd/panel/config/sites/002-cm.conf

git checkout ../rabbitmq/config/rabbitmng/20-user.conf

git checkout ../registry/config/config.yml

git pull


git submodule update --init --recursive
