#!/usr/bin/env bash
set -euo pipefail

source ./config

source ./functions


if [[ $# -ne 1 ]]; then

    echo "Informe { dev | tst | hom | ia }"

    exit 1

else

    domain $1

fi


git checkout ../httpd/panel/config/sites/000-default.conf
git checkout ../httpd/panel/config/sites/001-ci.conf
git checkout ../httpd/panel/config/sites/002-cm.conf
git checkout ../traefik/config/dynamic.toml
git checkout ../rabbitmq/config/rabbitmng/20-user.conf
git checkout ../registry/config/config.yml

git pull
git submodule update --init --recursive


if [[ -f ../traefik/.env ]]; then
    sed -i 's\@SVC_KEY\'$(docker run --rm --entrypoint htpasswd httpd -nb admin $(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../traefik/.env))'\g' ../traefik/config/dynamic.toml
    sed -i 's\@SVC_HOST\'$LAB_DOMAIN'\g' ../traefik/config/dynamic.toml


    sed -i 's\@CI_LAB_DOMAIN\'$CI_LAB_DOMAIN'\g' ../traefik/config/dynamic.toml
    sed -i 's\@CM_LAB_DOMAIN\'$CM_LAB_DOMAIN'\g' ../traefik/config/dynamic.toml
    sed -i 's\@ST_LAB_DOMAIN\'$ST_LAB_DOMAIN'\g' ../traefik/config/dynamic.toml
    sed -i 's\@ST_C_LAB_DOMAIN\'$ST_C_LAB_DOMAIN'\g' ../traefik/config/dynamic.toml
fi

[[ -f ../rabbitmq/.env ]] && sed -i 's/@SVC_PWD/'$(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../rabbitmq/.env)'/g' ../rabbitmq/config/rabbitmng/20-user.conf

if [[ -f ../registry/config/config.yml && -f ../redis/.env ]]; then
    sed -i 's/@LAB_DOMAIN/'$LAB_DOMAIN'/g' ../registry/config/config.yml
    sed -i 's/@REDIS_PWD/'$(awk -F'=' '$1 =="SVC_PWD" {print $2}' ../redis/.env)'/g' ../registry/config/config.yml
fi
