#!/usr/bin/env bash
set -euo pipefail

function create_user_noexpire() {

    sudo adduser --disabled-password --gecos "" $1
    sudo usermod --password $(echo s3cr37 | openssl passwd -1 -stdin) $1

}

function create_user() {

    sudo adduser --disabled-password --gecos "" $1
    sudo usermod --password $(echo s3cr37 | openssl passwd -1 -stdin) $1
    sudo passwd --expire $1

}

function create_operator() {

    create_user $1

    sudo usermod -a -G docker $1
    sudo usermod -a -G users $1

}

function nologin_operator() {

    create_operator $1
    
    usermod $1 -s /sbin/nologin

}

# User maint (já deve ter sido criado ao configurar o ambiente)
# create_user gpes
# usermod -aG sudo gpes

# User ansible
# create_user_noexpire ansible

# Professores SI-TIH
# create_user cunha
# create_user vieira
# create_user lineu
# create_user loubach
# create_user saotome

# Pesquisadores SI-TIH
# create_operator louro
# create_operator shigemura
# create_operator lippi
# create_operator max
# create_operator gomes
# create_operator vitor
# create_operator marcelo
# create_operator matheus

# Pesquisadores STAMPS
# create_operator gildarcio
# create_operator jean

# Professores IA-PLN
# create_nologin carlos
# create_nologin finger
# create_nologin ramirez
# create_nologin alves
# create_nologin navas

# Pesquisadores IA-PLN
# create_nologin carvalho
# create_nologin rodrigues
# create_nologin ribeiro
# create_nologin silva
