services:

  mysql01:
    container_name: mariadb01
    image: mariadb
    restart: unless-stopped
    ports:
      - '3401:3306'
    networks:
      netlab01:
        ipv4_address: ${MARIADB_HOST01}
    volumes:
      - mariadata01:/var/lib/mysql:rw
      - $PWD/mariadb01:/etc/mysql/conf.d:ro
    environment:
      - MARIADB_ROOT_PASSWORD=${SVC_PWD_01}
      - MARIADB_USER=maint
      - MARIADB_PASSWORD=${SVC_PWD_01}

  mysql02:
    container_name: mariadb02
    image: mariadb
    restart: unless-stopped
    ports:
      - '3402:3306'
    networks:
      netlab01:
        ipv4_address: ${MARIADB_HOST02}
    volumes:
      - mariadata02:/var/lib/mysql:rw
      - $PWD/mariadb02:/etc/mysql/conf.d:ro
    environment:
      - MARIADB_ROOT_PASSWORD=${SVC_PWD_02}
      - MARIADB_USER=maint
      - MARIADB_PASSWORD=${SVC_PWD_02}

volumes:
  mariadata01:
    name: mariadbdata01
    driver: local
  mariadata02:
    name: mariadbdata02
    driver: local
