#!/usr/bin/env bash
# set -euo pipefail

if [ "$EUID" -ne 0 ]
    then echo "Execute como root"
    exit 2
fi

crontab -r

export LAB_ENV=$(cat /export/lab)
echo "Configurando ambiente $LAB_ENV"

export SCHEDULE_BACKUP="0 0 * * 6"

TEMPFILE=`mktemp` && {
    crontab -l 2>/dev/null > $TEMPFILE
    echo "$SCHEDULE_BACKUP /home/gpes/LTS/maint/osupdate" >> $TEMPFILE
    crontab $TEMPFILE
    rm -f $TEMPFILE
}
