services:

  swirl:
    container_name: swirl
    image: cuigh/swirl
    restart: unless-stopped
    ports:
      - '8086:8001'
    networks:
      netlab01:
        ipv4_address: ${SWIRL_HOST}
    environment:
      DB_ADDRESS: mongodb://mongodb:27017/swirl
      DOCKER_ENDPOINT: tcp://swirl_manager_agent:2375
      AGENTS: swirl_manager_agent,swirl_worker_agent
    deploy:
      replicas: 2
      placement:
        constraints: [ node.role == worker ]

  manager_agent:
    image: cuigh/socat
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: [ node.role == manager ]

  worker_agent:
    image: cuigh/socat
    networks:
      - netlab01
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: [ node.role == worker ]
