services:

  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    restart: unless-stopped
    ports:
      - '9001:9001'
    networks:
      netlab01:
        ipv4_address: ${PORTAINERAGENT_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  netlab01:
    external: true
