services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    expose:
      - '9000'
    networks:
      - netlab01
    volumes:
      - portainerdata:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`${LAB_DOMAIN}`) && PathPrefix(`/portainer`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer
      - traefik.http.middlewares.portainer-stripprefix.stripprefix.forceSlash=true
      - traefik.http.routers.portainer.middlewares=portainer-stripprefix@docker

volumes:
  portainerdata:
    name: portainerdata
    external: true

networks:
  netlab01:
    external: true
