services:

  labelstudio:
    container_name: labelstudio
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    ports:
      - '8091:8080'
    networks:
      netlab01:
        ipv4_address: ${LABELSTUDIO_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
      - LOG_LEVEL=DEBUG
    volumes:
      - labelstudiodata:/label-studio/data:rw
    command: label-studio-uwsgi

volumes:
  labelstudiodata:
    name: labelstudiodata
    external: true

networks:
  netlab01:
    external: true
