services:

  backend:
    container_name: doccano_backend
    image: doccano/doccano:backend
    restart: unless-stopped
    networks:
      netlab01:
    volumes:
      - doccanostaticdata:/backend/staticfiles:rw
      - doccanomediadata:/backend/media:rw
      - doccanotmpdata:/backend/filepond-temp-uploads
      - $PWD/config:/doccano/backend/config/settings:ro
      - flualfadata:/label-studio/files/flualfa:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ADMIN_USERNAME=maint
      - ADMIN_PASSWORD=${SVC_PWD}
      - ADMIN_EMAIL=labqs@ita.br
      - DATABASE_URL=postgres://doccano:${POSTGRES_PWD}@postgres:5432/doccano?sslmode=disable
      - ALLOW_SIGNUP=False
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.production

  celery:
    container_name: doccano_celery
    image: doccano/doccano:backend
    networks:
      netlab01:
    volumes:
      - doccanomediadata:/backend/media
      - doccanotmpdata:/backend/filepond-temp-uploads
    entrypoint: ["/opt/bin/prod-celery.sh"]
    environment:
      PYTHONUNBUFFERED: "1"
      CELERY_BROKER_URL: "amqp://doccano:doccano@172.16.4.200:15672"
      DATABASE_URL: "postgres://doccano:${POSTGRES_PWD}@postgres:5432/doccano?sslmode=disable"
      DJANGO_SETTINGS_MODULE: "config.settings.production"

  flower:
    container_name: doccano_flower
    image: doccano/doccano:backend
    ports:
      - 5555:5555
    networks:
      netlab01:
    entrypoint: ["/opt/bin/prod-flower.sh"]
    environment:
      PYTHONUNBUFFERED: "1"
      CELERY_BROKER_URL: "amqp://doccano:doccano@172.16.4.200:15672"
      DATABASE_URL: "postgres://doccano:${POSTGRES_PWD}@postgres:5432/doccano?sslmode=disable"
      DJANGO_SETTINGS_MODULE: "config.settings.production"
      FLOWER_BASIC_AUTH: ""

  frontend:
    container_name: doccano_frontend
    image: doccano/doccano:frontend
    restart: unless-stopped
    ports:
      - '8092:8080'
    networks:
      netlab01:
        ipv4_address: ${DOCCANO_HOST}
    volumes:
      - doccanostaticdata:/static:rw
      - doccanomediadata:/media:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - API_URL=http://doccano_backend:8000
      - WORKER_PROCESSES=auto
    command: >
      /bin/sh -c "envsubst '$${WORKER_PROCESSES}'< /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

volumes:
  doccanostaticdata:
    name: doccanostaticdata
    external: true
  doccanomediadata:
    name: doccanomediadata
    external: true
  doccanotmpdata:
    name: doccanotmpdata
    external: true
  flualfadata:
    name: flualfadata
    external: true

networks:
  netlab01:
    external: true
