services:

  doccano:
    container_name: doccano
    image: doccano/doccano:backend
    restart: unless-stopped
    ports:
      - '8092:8000'
    networks:
      netlab01:
        ipv4_address: ${DOCCANO_HOST}
    volumes:
      - doccanostaticdata:/backend/staticfiles:rw
      - doccanomediadata:/backend/media:rw
      - $PWD/config:/doccano/backend/config/settings:ro
      - flualfadata:/label-studio/files/flualfa:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ADMIN_USERNAME='maint'
      - ADMIN_PASSWORD='${SVC_PWD}'
      - ADMIN_EMAIL='labqs@ita.br'
      - DATABASE_URL='postgres://doccano:${POSTGRES_PWD}@postgres:5432/doccano?sslmode=disable'
      - ALLOW_SIGNUP='False'
      - DEBUG='True'
      - DJANGO_SETTINGS_MODULE='config.settings.production'

volumes:
  doccanostaticdata:
    name: doccanostaticdata
    external: true
  doccanomediadata:
    name: doccanomediadata
    external: true
  flualfadata:
    name: flualfadata
    external: true

networks:
  netlab01:
    external: true
