services:

  redis-commander:
    container_name: commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - '8081:8081'
    networks:
      netlab01:
        ipv4_address: ${COMMANDER_HOST}
    volumes:
      - /usr/share/zoneinfo:/user/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - URL_PREFIX=/commander
