services:

  ansible:
    container_name: ansible
    image: ansible:local
    build:
      context: .
      dockerfile: ansible.Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    expose:
      - '22'
    networks:
      netlab01:
        ipv4_address: ${ANSIBLE_HOST}
    volumes:
      - ${PWD}/config:/etc/ansible:rw
      - ${PWD}/tasks:/home/ansible/tasks:rw
