services:

  nebula:
    container_name: nebula
    image: opennebula/opennebula:latest
    restart: unless-stopped
    ports:
      - '8001:8001'
      - '8443:8443'
    networks:
      netlab01:
        ipv4_address: ${NEBULA_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DEPLOY_SUNSTONE_EXTERNAL_PORT:8001
      - DEPLOY_SUNSTONE_EXTERNAL_TLS_PORT:8443

networks:
  netlab01:
    external: true
