services:

  nebula:
    container_name: nebula
    image: opennebula/opennebula:latest
    restart: unless-stopped
    ports:
      - '19999:19999'
    networks:
      netlab01:
        ipv4_address: ${NEBULA_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  netlab01:
    external: true
