services:

  console:
    container_name: console
    hostname: console
    image: minio/console:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    ports:
      - '8090:9090'
    networks:
      netlab01:
        ipv4_address: ${MINIO_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      CONSOLE_PBKDF_PASSPHRASE: ${SVC_PWD}
      CONSOLE_PBKDF_SALT: ${SVC_PBKDF_SALT}
      MINIO_CONSOLE_SUBPATH: https://${ST_LAB_DOMAIN}/console
      command: srv

networks:
  netlab01:
    external: true
