services:

  console:
    container_name: console
    hostname: console
    image: minio/console:latest
    restart: unless-stopped
    ports:
      - '8090:9090'
    networks:
      netlab01:
        ipv4_address: ${MINIO_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      CONSOLE_MINIO_SERVER: https://${ST_C_LAB_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.console.rule=Host(`${ST_C_LAB_DOMAIN}`) && PathPrefix(`/console`)
      - traefik.http.routers.console.tls=true
      - traefik.http.services.console.loadbalancer.server.port=9090
      - traefik.http.middlewares.console-stripprefix.stripprefix.prefixes=/console
      - traefik.http.middlewares.console-stripprefix.stripprefix.forceSlash=true
      - traefik.http.routers.console.middlewares=console-stripprefix@docker
    command: server

networks:
  netlab01:
    external: true
