services:

  console:
    container_name: console
    hostname: console
    image: minio/console:latest
    restart: unless-stopped
    expose:
      - '9090'
    networks:
      - netlab01
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      CONSOLE_MINIO_SERVER: https://${ST_LAB_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.console.rule=Host(`${ST_C_LAB_DOMAIN}`)
      - traefik.http.routers.console.tls=true
      - traefik.http.services.console.loadbalancer.server.port=9090
    command: server

networks:
  netlab01:
    external: true
