services:

  console:
    container_name: console
    hostname: console
    image: minio/console:latest
    restart: unless-stopped
    ports:
      - '8090:9090'
    networks:
      netlab01:
        ipv4_address: ${MINIO_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      CONSOLE_MINIO_SERVER: https://${ST_LAB_DOMAIN}
    command: server

networks:
  netlab01:
    external: true
