services:

  console:
    container_name: kes
    hostname: kes
    image: minio/kes:latest
    restart: unless-stopped
    ports:
      - '7373:7373'
    networks:
      netlab01:
        ipv4_address: ${MINIO_HOST_KES}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: server

networks:
  netlab01:
    external: true
