services:

  kes:
    container_name: kes
    image: minio/kes:latest
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    ports:
      - '7373:7373'
    networks:
      netlab01:
        ipv4_address: ${KES_HOST}
    volumes:
      - $PWD/config/kes:/root/.kes/config
      - kesdata:/root/.kes/certs:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KES_SERVER=https://127.0.0.1:7373
      - KES_CLIENT_KEY=/root/.kes/certs/private.key
      - KES_CLIENT_CERT=/root/.kes/certs/public.crt
    command: server --config=/root/.kes/config/config.yaml --auth=off 

  minio01:
    container_name: minio01
    hostname: minio01
    image: minio/minio:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    expose:
      - '9000'
    networks:
      netlab01:
        ipv4_address: ${MINIO_HOST01}
    volumes:
      - miniodata011:/data/vol1:rw
      - miniodata012:/data/vol2:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      MINIO_ROOT_USER: maint
      MINIO_ROOT_PASSWORD: ${SVC_PWD}
      MINIO_BROWSER: off
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio01.rule=Host(`${ST_LAB_DOMAIN}`)
      - traefik.http.routers.minio01.tls=true
      - traefik.http.services.minio01.loadbalancer.server.port=9000
    command: server --address ":9000" http://minio0{1...2}/data/vol{1...2}

  minio02:
    container_name: minio02
    hostname: minio02
    image: minio/minio:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    expose:
      - '9000'
    networks:
      netlab01:
        ipv4_address: ${MINIO_HOST02}
    volumes:
      - miniodata021:/data/vol1:rw
      - miniodata022:/data/vol2:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      MINIO_ROOT_USER: maint
      MINIO_ROOT_PASSWORD: ${SVC_PWD}
      MINIO_BROWSER: off
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio02.rule=Host(`${ST_LAB_DOMAIN}`)
      - traefik.http.routers.minio02.tls=true
      - traefik.http.services.minio02.loadbalancer.server.port=9000
    command: server --address ":9000" http://minio0{1...2}/data/vol{1...2}

networks:
  netlab01:
    external: true

volumes:
  kesdata:
    name: kesdata
    external: true
  miniodata0101:
    name: miniodata011
    external: true
  miniodata0102:
    name: miniodata012
    external: true
  miniodata0201:
    name: miniodata021
    external: true
  miniodata0202:
    name: miniodata022
    external: true
