services:

  minio01:
    container_name: minio01
    image: minio/minio:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      netlab01:
        ipv4_address: ${MARIADB_HOST}
    volumes:
      - miniodata011:/data1:rw
      - miniodata012:/data2:rw
      - $PWD/mariadb/config:/etc/mysql/conf.d:ro
      - $PWD/mariadb/init:/docker-entrypoint-initdb.d:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      MINIO_ROOT_USER: maint
      MINIO_ROOT_PASSWORD: ${SVC_PWD}

  minio02:
    container_name: minio02
    image: minio/minio:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      netlab01:
        ipv4_address: ${MARIADB_HOST}
    volumes:
      - miniodata021:/data1:rw
      - miniodata022:/data2:rw
      - $PWD/mariadb/config:/etc/mysql/conf.d:ro
      - $PWD/mariadb/init:/docker-entrypoint-initdb.d:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      MINIO_ROOT_USER: maint
      MINIO_ROOT_PASSWORD: ${SVC_PWD}

  minio03:
    container_name: minio03
    image: minio/minio:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      netlab01:
        ipv4_address: ${MARIADB_HOST}
    volumes:
      - miniodata031:/data1:rw
      - miniodata032:/data2:rw
      - $PWD/mariadb/config:/etc/mysql/conf.d:ro
      - $PWD/mariadb/init:/docker-entrypoint-initdb.d:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      MINIO_ROOT_USER: maint
      MINIO_ROOT_PASSWORD: ${SVC_PWD}

  minio04:
    container_name: minio04
    image: minio/minio:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      netlab01:
        ipv4_address: ${MARIADB_HOST}
    volumes:
      - miniodata041:/data1:rw
      - miniodata042:/data2:rw
      - $PWD/mariadb/config:/etc/mysql/conf.d:ro
      - $PWD/mariadb/init:/docker-entrypoint-initdb.d:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    environment:
      MINIO_ROOT_USER: maint
      MINIO_ROOT_PASSWORD: ${SVC_PWD}

volumes:
  miniodata0101:
    name: miniodata011
    external: true
  miniodata0102:
    name: miniodata012
    external: true
  miniodata0201:
    name: miniodata021
    external: true
  miniodata0202:
    name: miniodata022
    external: true
  miniodata0301:
    name: miniodata031
    external: true
  miniodata0302:
    name: miniodata032
    external: true
  miniodata0401:
    name: miniodata041
    external: true
  miniodata0402:
    name: miniodata042
    external: true

networks:
  netlab01:
    external: true
