services:

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    ports:
      - '6300:6379'
    networks:
      netlab01:
        ipv4_address: ${REDIS_HOST}
    volumes:
      - $PWD/config:/usr/local/etc/redis/redis.conf:ro
      - redisdata:/data:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_REPLICATION_MODE: master
      REDISCLI_AUTH: ${SVC_PWD}
    command: ["redis-server", "--requirepass", "${SVC_PWD}", "--appendonly", "yes"]

  redis01:
    container_name: redis01
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    ports:
      - '6301:6379'
    networks:
      netlab01:
        ipv4_address: ${REDIS_HOST01}
    volumes:
      - $PWD/config:/usr/local/etc/redis/redis.conf:ro
      - redisdata01:/data:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_REPLICATION_MODE: master
      REDISCLI_AUTH: ${SVC_PWD_01}
    command: ["redis-server", "--requirepass", "${SVC_PWD_01}", "--appendonly", "yes"]

  redis02:
    container_name: redis02
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    ports:
      - '6302:6379'
    networks:
      netlab01:
        ipv4_address: ${REDIS_HOST02}
    volumes:
      - $PWD/config:/usr/local/etc/redis/redis.conf:ro
      - redisdata02:/data:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_REPLICATION_MODE: master
      REDISCLI_AUTH: ${SVC_PWD_02}
    command: ["redis-server", "--requirepass", "${SVC_PWD_02}", "--appendonly", "yes"]
  
volumes:
  redisdata:
    name: redisdata
    external: true
  redisdata01:
    name: redisdata01
    external: true
  redisdata02:
    name: redisdata02
    external: true

networks:
  netlab01:
    external: true
