services:

  semaphore:
    container_name: semaphore
    image: labqs/semaphore:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: semaphorebase
    restart: unless-stopped
    ports:
      - '8085:3000'
    networks:
      netlab01:
        ipv4_address: ${SEMAPHORE_HOST}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${POSTGRES_PWD}
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB: semaphore?sslmode=disable
      SEMAPHORE_ADMIN: maint
      SEMAPHORE_ADMIN_PASSWORD: ${SVC_PWD}
      SEMAPHORE_ADMIN_NAME: maint
      SEMAPHORE_ADMIN_EMAIL: labqs@ita.br

networks:
  netlab01:
    external: true
