services:

  semaphore:
    container_name: semaphore
    image: labqs/semaphore:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: semaphorebase
    restart: unless-stopped
    ports:
      - ':8080'
    networks:
      - netlab01
    volumes:
      - $PWD/config:/etc/semaphore:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${POSTGRES_PWD}
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB: semaphore?sslmode=disable
      SEMAPHORE_ADMIN: maint
      SEMAPHORE_ADMIN_PASSWORD: ${SVC_PWD}
      SEMAPHORE_ADMIN_NAME: maint
      SEMAPHORE_ADMIN_EMAIL: labqs@ita.br
    labels:
      - traefik.enable=true
      - traefik.http.routers.semaphore.rule=Host(`${CM_LAB_DOMAIN}`)
      - traefik.http.routers.semaphore.tls=true
      - traefik.http.routers.semaphore.tls.certresolver=le
      - traefik.http.services.semaphore.loadbalancer.server.port=2222

networks:
  netlab01:
    external: true
