services:

  semaphore:
    container_name: semaphore
    image: ansiblesemaphore/semaphore:latest
    command: 
      - sh -c "python3 -m ensurepip"
      - sh -c "/sbin/tini -- /usr/local/bin/semaphore-wrapper /usr/local/bin/semaphore server --config /etc/semaphore/config.json"
    restart: unless-stopped
    ports:
      - '8085:3000'
    networks:
      netlab01:
        ipv4_address: ${SEMAPHORE_HOST}
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${POSTGRES_PWD}
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB: semaphore?sslmode=disable
      SEMAPHORE_ADMIN: maint
      SEMAPHORE_ADMIN_PASSWORD: ${SVC_PWD}
      SEMAPHORE_ADMIN_NAME: maint
      SEMAPHORE_ADMIN_EMAIL: maint@ita.br
