services:

  semaphore:
    container_name: semaphore
    image: ansiblesemaphore/semaphore:latest
    restart: unless-stopped
    ports:
      - '8085:3000'
    networks:
      netlab01:
        ipv4_address: ${SEMAPHORE_HOST}
    environment:
      SEMAPHORE_WEB_ROOT: https://{$LAB_DOMAIN}/semaphore
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${POSTGRES_PWD}
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB: semaphore?sslmode=disable
      SEMAPHORE_ADMIN: maint
      SEMAPHORE_ADMIN_PASSWORD: ${SVC_PWD}
      SEMAPHORE_ADMIN_NAME: maint
      SEMAPHORE_ADMIN_EMAIL: gomesjm@ita.br
